[build]
  command = "npm install"
  publish = "."

[functions]
  external_node_modules = ["express", "cors", "node-fetch", "uuid", "dotenv"]
  node_bundler = "esbuild"

# No need for this redirect anymore since we're handling the paths in the function itself

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200