services:
  - type: web
    name: ai-image-generator
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: STABILITY_API_KEY
        sync: false # This means you'll set it manually in the Render dashboard
    autoDeploy: false